version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-tutorial'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_HOST: rabbitmq